/**
 * Represents an authenticated account within OpenCore Identity.
 * This entity is storage-agnostic and maps directly to the accounts table.
 */
export interface Account {
  /** Numeric primary key for internal references and joins. */
  id: number;
  /** Optional linked ID - can be UUID (local) or external API ID. Auto-generated by default. */
  linkedId: string | null;
  /** Source of the account: 'local', 'api', or custom identifier. */
  externalSource?: string;

  /** Rockstar license identifier (preferred). */
  license: string | null;
  /** Discord user ID. */
  discord: string | null;
  /** Steam hex identifier. */
  steam: string | null;

  /** Optional display name or username. */
  username: string | null;

  /** Role assignment (FK to roles table). */
  roleId: number | null;

  /** Custom permissions specific to this account (overrides/additions to role permissions). */
  customPermissions: string[];

  /** Creation timestamp. */
  createdAt: Date;
  /** Last successful login timestamp. */
  lastLoginAt: Date;

  /** Ban status flag. */
  banned: boolean;
  /** Ban reason text when banned. */
  banReason: string | null;
  /** Ban expiration (null means permanent). */
  banExpires: Date | null;
}
